# Assignment 13 & 14

In [1]:
import re

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('network_logs.csv')

In [4]:
df.head()

,network_name,packets_transmitted,received,bandwidth_category,ping_urls_encrypted,date,room,hint_ip
0,net_1.1,10,10,speed_1,PLsm0751_20481jdaLd,1632701211,sn_1,192.168.1.1
1,net_1.1,10,10,speed_1,PLsm1751_21481jdaLd,1632701211,sn_1,192.168.1.1
2,net_1.1,10,10,speed_1,PLsm2751_22481jdaLd,1632701211,sn_1,192.168.1.1
3,net_1.1,10,10,speed_1,PLsm3751_23481jdaLd,1632701211,sn_1,192.168.1.1
4,net_1.1,10,10,speed_1,PLsm4751_24481jdaLd,1632701211,sn_1,192.168.1.1

In [5]:
df['network_name'] = df['network_name'].replace(to_replace = "[a-z]+_", value ='192.168.', regex = True)

In [6]:
df.head(10)

,network_name,packets_transmitted,received,bandwidth_category,ping_urls_encrypted,date,room,hint_ip
0,192.168.1.1,10,10,speed_1,PLsm0751_20481jdaLd,1632701211,sn_1,192.168.1.1
1,192.168.1.1,10,10,speed_1,PLsm1751_21481jdaLd,1632701211,sn_1,192.168.1.1
2,192.168.1.1,10,10,speed_1,PLsm2751_22481jdaLd,1632701211,sn_1,192.168.1.1
3,192.168.1.1,10,10,speed_1,PLsm3751_23481jdaLd,1632701211,sn_1,192.168.1.1
4,192.168.1.1,10,10,speed_1,PLsm4751_24481jdaLd,1632701211,sn_1,192.168.1.1
5,192.168.1.1,10,10,speed_1,PLsm5751_25481jdaLd,1632701211,sn_1,192.168.1.1
6,192.168.1.1,10,10,speed_1,PLsm6751_26481jdaLd,1632701211,sn_1,192.168.1.1
7,192.168.1.1,10,10,speed_1,PLsm7751_27481jdaLd,1632701211,sn_1,192.168.1.1
8,192.168.1.1,10,10,speed_1,PLsm8751_28481jdaLd,1632701211,sn_1,192.168.1.1
9,192.168.1.1,10,4,speed_1,PLsm9751_29481jdaLd,1632701211,sn_1,192.168.1.1

In [7]:
df.tail(10)

,network_name,packets_transmitted,received,bandwidth_category,ping_urls_encrypted,date,room,hint_ip
55990,192.168.17.14,10,10,speed_1,PLsm1907514_21904814jdaLd,1632701211,sn_14,192.168.17.14
55991,192.168.17.14,10,10,speed_1,PLsm1917514_21914814jdaLd,1632701211,sn_14,192.168.17.14
55992,192.168.17.14,10,10,speed_1,PLsm1927514_21924814jdaLd,1632701211,sn_14,192.168.17.14
55993,192.168.17.14,10,10,speed_1,PLsm1937514_21934814jdaLd,1632701211,sn_14,192.168.17.14
55994,192.168.17.14,10,10,speed_1,PLsm1947514_21944814jdaLd,1632701211,sn_14,192.168.17.14
55995,192.168.17.14,10,10,speed_1,PLsm1957514_21954814jdaLd,1632701211,sn_14,192.168.17.14
55996,192.168.17.14,10,10,speed_1,PLsm1967514_21964814jdaLd,1632701211,sn_14,192.168.17.14
55997,192.168.17.14,10,10,speed_1,PLsm1977514_21974814jdaLd,1632701211,sn_14,192.168.17.14
55998,192.168.17.14,10,10,speed_1,PLsm1987514_21984814jdaLd,1632701211,sn_14,192.168.17.14
55999,192.168.17.14,10,10,speed_1,PLsm1997514_21994814jdaLd,1632701211,sn_14,192.168.17.14

In [8]:
df.rename(columns = {'network_name':'origianl_ip_name'}, inplace = True)

In [9]:
df.head()

,origianl_ip_name,packets_transmitted,received,bandwidth_category,ping_urls_encrypted,date,room,hint_ip
0,192.168.1.1,10,10,speed_1,PLsm0751_20481jdaLd,1632701211,sn_1,192.168.1.1
1,192.168.1.1,10,10,speed_1,PLsm1751_21481jdaLd,1632701211,sn_1,192.168.1.1
2,192.168.1.1,10,10,speed_1,PLsm2751_22481jdaLd,1632701211,sn_1,192.168.1.1
3,192.168.1.1,10,10,speed_1,PLsm3751_23481jdaLd,1632701211,sn_1,192.168.1.1
4,192.168.1.1,10,10,speed_1,PLsm4751_24481jdaLd,1632701211,sn_1,192.168.1.1

In [12]:
df['date'] = pd.to_datetime(df['date']).dt.date

In [13]:
df.head()

,origianl_ip_name,packets_transmitted,received,bandwidth_category,ping_urls_encrypted,date,room,hint_ip
0,192.168.1.1,10,10,speed_1,PLsm0751_20481jdaLd,1970-01-01,sn_1,192.168.1.1
1,192.168.1.1,10,10,speed_1,PLsm1751_21481jdaLd,1970-01-01,sn_1,192.168.1.1
2,192.168.1.1,10,10,speed_1,PLsm2751_22481jdaLd,1970-01-01,sn_1,192.168.1.1
3,192.168.1.1,10,10,speed_1,PLsm3751_23481jdaLd,1970-01-01,sn_1,192.168.1.1
4,192.168.1.1,10,10,speed_1,PLsm4751_24481jdaLd,1970-01-01,sn_1,192.168.1.1

In [14]:
df.tail()

,origianl_ip_name,packets_transmitted,received,bandwidth_category,ping_urls_encrypted,date,room,hint_ip
55995,192.168.17.14,10,10,speed_1,PLsm1957514_21954814jdaLd,1970-01-01,sn_14,192.168.17.14
55996,192.168.17.14,10,10,speed_1,PLsm1967514_21964814jdaLd,1970-01-01,sn_14,192.168.17.14
55997,192.168.17.14,10,10,speed_1,PLsm1977514_21974814jdaLd,1970-01-01,sn_14,192.168.17.14
55998,192.168.17.14,10,10,speed_1,PLsm1987514_21984814jdaLd,1970-01-01,sn_14,192.168.17.14
55999,192.168.17.14,10,10,speed_1,PLsm1997514_21994814jdaLd,1970-01-01,sn_14,192.168.17.14